# Generated by Django 2.2.6 on 2019-10-04 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='ToDoItems',
        ),
        migrations.RenameField(
            model_name='todoitems',
            old_name='item',
            new_name='text',
        ),
    ]
