# Generated by Django 2.1.7 on 2019-10-07 17:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_auto_20191004_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitems',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 7, 17, 56, 52, 130318, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
